### PR TITLE
Happly upgrade +  fix

### PR DESCRIPTION
**Pull request by dcoeurjo**
This PR upgrades happly's version of geometry-central to the current master (with a quick fix on the ply_wrapper).

The previous version happly generates build issues (virtual destructor one) that have been fixed in the master (which also makes polyscope impossible to build on mac with the latest clang).

### CODE REVIEW

**Comment by dcoeurjo** [comment]
(if the PR gets merged, it may also be interesting to upgrade GC version in Polyscope :))

**Comment by nmwsharp** [comment]
Great, thanks!

**Comment by nmwsharp** [comment]
Also updated polyscope submodule version :D https://github.com/nmwsharp/polyscope/commit/71d30883eedf4eac774fb5169de63324c52dfe01

**Comment by dcoeurjo** [comment]
👌thx

**Pull request merged**
